-- Battle timeline and animation audit (read-only). Run from the Gen1Recomp
-- root with luajit:
--   luajit mods/STADIUM2_IMPORTER/tools/audit_battle_timeline.lua > out.md
-- STADIUM2_ROM (default baseroms/stadium2.z64); STADIUM2_PACK_DIR, the
-- importer's cache "normal" folder (NNN.lua packs), enables the clip checks.
--
-- Native timeline per move and attacker species (30 Hz ticks from the move
-- record's dispatch; US asm, pret c0e10f2):
--   84114A04: counter 0, or the hit frame when negative (pre-roll); +0x619
--     and +0x61A are rebased by +0x61B (row byte 6, the clip start).
--   84114BF4: route (84114600 -> 84108728) at counter +0x619 (byte 0x0B);
--     84112564 sets record +1 bit 0 (text and HP bars start, 84137778 /
--     84136D9C) at the "release" frame; the attack ends at +0x61A (byte
--     0x0A), or when its clip ends when that is 0, clearing the timer.
--   84135778: the next record (the defender's 0x0A hit) loads only when the
--     timer (+6) is 0, the new-event flag, the HP bars and the text gate are
--     clear; it is dispatched the next frame (8413D37C order).
--   841170A0 / 84118138: the defender's counter starts at 0 (its hit clip,
--     context 254, at counter 0), and 841087B8 (impact route) fires at the
--     defender's own row byte 7 (84116BC0).
-- So the native impact is at least attackEnd + 1 + byte7; the port
-- (Sequence.attackTiming) schedules release + byte7 from the move start.
package.path="./?.lua;./?/init.lua;"..package.path
local P="mods.STADIUM2_IMPORTER.lib."
local Dispatch=require(P.."animation_dispatch")
local Sequence=require(P.."stadium2_battle_fx_sequence")
local Special=require(P.."battle_special_moves")
local romPath=os.getenv("STADIUM2_ROM") or "mods/STADIUM2_IMPORTER/baseroms/stadium2.z64"
local f=assert(io.open(romPath,"rb"),"ROM unavailable: "..romPath)
local rom=f:read("*a") f:close()
local names=assert(Dispatch.moveNames(rom))

local rows={}
for species=1,251 do rows[species]=assert(Dispatch.forSpecies(rom,species)) end
local function bytesOf(species)
  local raw={}
  local r=rows[species]
  for i=0,r.n-1 do raw[#raw+1]=r[i].raw end
  return table.concat(raw)
end
local dispatch={}
for species=1,251 do dispatch[species]=bytesOf(species) end

-- optional model packs: clips per species
local packs={}
local packDir=os.getenv("STADIUM2_PACK_DIR")
if packDir then
  local Pack=require(P.."pack")
  for species=1,251 do
    local chunk=loadfile(("%s/%03d.lua"):format(packDir,species))
    local ok,data=pcall(chunk or function() end)
    if ok and type(data)=="table" and data.bytes then
      local model=Pack.parse(data.bytes)
      if model then packs[species]=model end
    end
  end
end
local Pack=packDir and require(P.."pack")

local function s8(v) v=v%256 return v>=0x80 and v-0x100 or v end
local function stats(list)
  if #list==0 then return nil end
  table.sort(list)
  return {min=list[1],med=list[math.floor((#list+1)/2)],max=list[#list],n=#list}
end
local function fmt(s) if not s then return "-" end
  return s.min==s.max and tostring(s.min) or ("%d / %d / %d"):format(s.min,s.med,s.max) end

-- 84114804's behaviour kinds (battle-special-moves.md) and the port's.
local KINDS={[0x39]=0xA,[0x42]=4,[0x45]=8,[0x60]=0xD,[0x61]=6,[0x68]=7,[0x6E]=0xC,
  [0x7F]=0xE,[0xB9]=0x19,[0xE5]=0x13,[0x6B]=9,[0xBB]=0x1A,[0xC2]=0x18}
local DEFENDER_KINDS={[0x17]=0xF,[0x22]=0xF}

print("# Battle timeline and animation audit")
print()
print("Generated by tools/audit_battle_timeline.lua from the US ROM"..(packDir and " and the importer's model packs" or "")..".")
print("Ticks are 30 Hz frames from the move record's dispatch; triples are min / median / max over the species whose row names a clip (Species column).")
print("Early = (native impact lower bound) - (port impact): attackEnd + 1 - release.")
print()
print("| # | Move | Species | Route | Release | Attack end | Port impact early by | Clip end used | Clip missing | Kind |")
print("|---|---|---|---|---|---|---|---|---|---|")
local totals={early=0,moves=0,noClip=0}
for move=1,251 do
  local route,release,ends,early,clipEnds,noClip,noHit={}, {}, {}, {}, 0, 0, 0
  for species=1,251 do
    local d=dispatch[species]
    local base=(move-1)*20
    local start,hit,second=d:byte(base+7),s8(d:byte(base+0x0C)),d:byte(base+0x0B)
    -- only rows that name a body clip (byte 0 ~= 0xFF): the species has an
    -- animation for this move
    local usable=d:byte(base+1)~=0xFF
    local t=usable and Sequence.attackTiming(d,move,{species=species}) or nil
    if t and t.route then
      route[#route+1]=t.route
      local counter0=hit<0 and hit or 0
      local rebSecond=(second-start)%256
      local finish
      local model=packs[species]
      if rebSecond~=0 then finish=rebSecond-counter0
      else
        clipEnds=clipEnds+1
        local index=model and Pack.moveIndex(model,move)
        local anim=index and model.anims[index]
        finish=anim and (anim.frames-start-counter0) or nil
      end
      if t.release then release[#release+1]=t.release end
      if finish then
        ends[#ends+1]=finish
        if t.release then early[#early+1]=finish+1-t.release end
      end
    end
    local model=packs[species]
    -- a row that names a clip the imported model lacks: the port falls back
    -- to a generic clip (Actor:attack), not Stadium behaviour
    if model and usable and not Pack.moveIndex(model,move) then noClip=noClip+1 end
  end
  local e=stats(early)
  if e and e.med>0 then totals.early=totals.early+1 end
  totals.moves=totals.moves+1
  totals.noClip=totals.noClip+noClip
  local kind=KINDS[move] or DEFENDER_KINDS[move]
  local kindText="-"
  if kind then
    local ported=(KINDS[move] and Special.KINDS[move]) or (move==107)
    kindText=("0x%X%s%s"):format(kind,DEFENDER_KINDS[move] and " (defender)" or "",ported and " ported" or " NOT ported")
  end
  print(("| %d | %s | %d | %s | %s | %s | %s | %d | %s | %s |"):format(move,names[move],#route,
    fmt(stats(route)),fmt(stats(release)),fmt(stats(ends)),fmt(e),clipEnds,
    packDir and tostring(noClip) or "?",kindText))
end
print()
print(("Summary: %d of %d moves fire the impact early in the port (median > 0)."):format(totals.early,totals.moves))
if packDir then
  print(("Rows naming a clip the imported model lacks (generic fallback used): %d."):format(totals.noClip))
  local noHit={}
  for species=1,251 do
    local model=packs[species]
    if model and not Pack.contextIndex(model,"hit") then noHit[#noHit+1]=species end
  end
  print(("Species without a hit clip (context 254): %d%s."):format(#noHit,#noHit>0 and (" ("..table.concat(noHit,", ")..")") or ""))
  local loaded=0 for _ in pairs(packs) do loaded=loaded+1 end
  print(("Model packs read: %d of 251."):format(loaded))
end
