#!/usr/bin/env python3
"""Convert selected Kenney CC0 cave pieces into the shared static mesh format."""
from pathlib import Path
import argparse
import shutil


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('pack', type=Path)
    args = parser.parse_args()
    out = Path(__file__).resolve().parents[1] / 'assets/kenney_cave'
    out.mkdir(parents=True, exist_ok=True)
    lines = ['-- Kenney Modular Cave Kit (CC0). Generated by tools/build_kenney_cave.py.', 'return {']
    for name in ['template-wall', 'template-detail', 'gate-rock', 'rock_smallA']:
        pack = args.pack.parent / 'Nature Kit' if name == 'rock_smallA' else args.pack
        points, normals, rows = [], [], []
        for line in (pack / 'Models/OBJ format' / (name + '.obj')).read_text().splitlines():
            fields = line.split()
            if not fields:
                continue
            if fields[0] == 'v':
                points.append(list(map(float, fields[1:4])))
            elif fields[0] == 'vn':
                normals.append(list(map(float, fields[1:4])))
            elif fields[0] == 'f':
                face = [f.split('/') for f in fields[1:]]
                for i in range(1, len(face) - 1):
                    for vertex in (face[0], face[i], face[i+1]):
                        row = points[int(vertex[0])-1] + normals[int(vertex[2])-1]
                        rows.append('{' + ','.join(format(v, '.6g') for v in row) + '},')
        lines += ['["' + name + '"]={'] + rows + ['},']
        print(name, len(rows)//3, 'triangles')
    lines += ['}']
    (out / 'models.lua').write_text('\n'.join(lines)+'\n')
    shutil.copyfile(args.pack/'License.txt', out/'License.txt')


if __name__ == '__main__':
    main()
