#!/usr/bin/env python3
"""Bake Kenney Pirate Kit / Watercraft palette UVs into vertex colors and
material IDs for the ocean scene's shared watercolor material pass.

Material IDs (match lib/battle_ocean.lua):
  1 foliage (leaf wash)   2 wood (bark wash)   3 stone (stone wash)
  4 sand (paper wash)     5 cloth/sail (paper wash, light)   6 painted trim
"""
from pathlib import Path
import argparse
import colorsys
import shutil
from PIL import Image

MODELS = {
    # name: (pack, source file)
    'palm-bend': ('Pirate Kit', 'palm-bend'),
    'palm-straight': ('Pirate Kit', 'palm-straight'),
    'palm-detailed-bend': ('Pirate Kit', 'palm-detailed-bend'),
    'rocks-a': ('Pirate Kit', 'rocks-a'),
    'rocks-b': ('Pirate Kit', 'rocks-b'),
    'rocks-c': ('Pirate Kit', 'rocks-c'),
    'dock': ('Pirate Kit', 'structure-platform-dock'),
    'dock-small': ('Pirate Kit', 'structure-platform-dock-small'),
    'boat-row-small': ('Pirate Kit', 'boat-row-small'),
    'barrel': ('Pirate Kit', 'barrel'),
    'crate': ('Pirate Kit', 'crate'),
    'grass-plant': ('Pirate Kit', 'grass-plant'),
    'boat-sail': ('Watercraft Pack', 'boat-sail-a'),
    'boat-fishing': ('Watercraft Pack', 'boat-fishing-small'),
}


def classify(rgb):
    r, g, b = (c / 255 for c in rgb)
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    h *= 360
    if v > .82 and s < .18:
        return 5  # sails, cloth, white paint
    if 70 <= h <= 170 and s > .25:
        return 1  # palm fronds, grass
    if s < .24:
        return 3  # blue-grey rock
    if 19.5 <= h <= 45 and s < .52:
        return 4  # sand on the beach rocks
    if h < 16 and s > .65:
        return 6  # red paint on the boats
    if h <= 25 or h >= 340:
        return 2  # Kenney's orange-brown wood and trunks
    return 6


def convert(path, palette):
    positions, normals, uvs, rows = [], [], [], []
    for line in path.read_text().splitlines():
        f = line.split()
        if not f:
            continue
        if f[0] == 'v':
            positions.append(list(map(float, f[1:4])))
        elif f[0] == 'vn':
            normals.append(list(map(float, f[1:4])))
        elif f[0] == 'vt':
            uvs.append(list(map(float, f[1:3])))
        elif f[0] == 'f':
            face = [v.split('/') for v in f[1:]]
            for i in range(1, len(face) - 1):
                triangle = (face[0], face[i], face[i + 1])
                colors = []
                for v in triangle:
                    u, t = uvs[int(v[1]) - 1]
                    colors.append(palette.getpixel((
                        min(palette.width - 1, max(0, int(u * palette.width))),
                        min(palette.height - 1, max(0, int((1 - t) * palette.height))))))
                mean = tuple(sum(c[k] for c in colors) / 3 for k in range(3))
                material = classify(mean)
                for v in triangle:
                    row = positions[int(v[0]) - 1] + normals[int(v[2]) - 1] \
                        + [c / 255 for c in mean] + [material]
                    rows.append('{' + ','.join(format(x, '.6g') for x in row) + '},')
    return rows


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('assets', type=Path, help="the All-in-1 '3D assets' directory")
    args = parser.parse_args()
    out = Path(__file__).resolve().parents[1] / 'assets/kenney_ocean'
    out.mkdir(parents=True, exist_ok=True)
    lines = ['-- Kenney Pirate Kit and Watercraft Pack (CC0). Generated by',
             '-- tools/build_kenney_ocean.py: palette colors and material IDs.', 'return {']
    for name, (pack, source) in MODELS.items():
        base = args.assets / pack / 'Models/OBJ format'
        palette = Image.open(base / 'Textures/colormap.png').convert('RGB')
        rows = convert(base / (source + '.obj'), palette)
        lines += ['["' + name + '"]={'] + rows + ['},']
        print(name, len(rows) // 3)
    (out / 'models.lua').write_text('\n'.join(lines + ['}']) + '\n')
    shutil.copyfile(args.assets / 'Pirate Kit/License.txt', out / 'Pirate-Kit-License.txt')
    shutil.copyfile(args.assets / 'Watercraft Pack/License.txt', out / 'Watercraft-License.txt')


if __name__ == '__main__':
    main()
